[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://ai-workplace-api.herokuapp.com/api"
  REACT_APP_SUPABASE_URL = "https://amlvbkpahfjqymmhrpxy.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbHZia3BhaGZqcXltbWhycHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDA1MTUsImV4cCI6MjA2OTQxNjUxNX0.hgV1oMUYaSYs_LOOmckVkF16iEqrlbs4Csk_cgUX8yg"

# 重定向规则 - 支持React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
