[build]
  # 构建命令
  command = "npm run build"
  # 构建输出目录
  publish = "client/build"
  # 构建前的准备工作
  base = "client"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"
  # 构建环境变量
  REACT_APP_API_URL = "https://ai-workplace-api.herokuapp.com/api"
  GENERATE_SOURCEMAP = "false"

# 重定向规则 - 支持React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API代理设置（开发环境）
[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.supabase.co https://*.supabase.co"

# 静态资源缓存
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML文件缓存
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 服务工作者缓存
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 错误页面
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# 表单处理
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# 函数设置（如果使用Netlify Functions）
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# 插件配置
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://ai-workplace-genie.netlify.app"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing"
    ]

# 环境变量（生产环境）
[context.production.environment]
  REACT_APP_ENV = "production"
  REACT_APP_API_URL = "https://ai-workplace-api.herokuapp.com/api"
  REACT_APP_SUPABASE_URL = "https://amlvbkpahfjqymmhrpxy.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbHZia3BhaGZqcXltbWhycHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDA1MTUsImV4cCI6MjA2OTQxNjUxNX0.ILqs3LLjQTvkJ5Qp4icEHA_zNBwa7TB"

# 环境变量（预览环境）
[context.deploy-preview.environment]
  REACT_APP_ENV = "preview"
  REACT_APP_API_URL = "https://ai-workplace-api-staging.herokuapp.com/api"

# 环境变量（分支部署）
[context.branch-deploy.environment]
  REACT_APP_ENV = "development"
  REACT_APP_API_URL = "http://localhost:5000/api"

# 分支特定设置
[context.staging]
  command = "npm run build:staging"
  
[context.staging.environment]
  REACT_APP_ENV = "staging"
  REACT_APP_API_URL = "https://ai-workplace-api-staging.herokuapp.com/api"

# 开发分支设置
[context.develop]
  command = "npm run build:dev"
  
[context.develop.environment]
  REACT_APP_ENV = "development"
  REACT_APP_API_URL = "http://localhost:5000/api"
  REACT_APP_DEBUG = "true"